version: '3.3'

services:
  keycloak:
    image: jboss/keycloak:6.0.0
    ports:
      - 8180:8080
    environment:
      - KEYCLOAK_USER=activage
      - KEYCLOAK_PASSWORD=activage
      - DB_VENDOR=postgres
      - DB_ADDR=keycloak-postgres-database
      - DB_PORT=5432
      - DB_DATABASE=keycloak
      - DB_USER=keycloak
      - DB_PASSWORD=keycloak
      - ROOT_LOGLEVEL=DEBUG
      #       Import parameters
      - KEYCLOAK_IMPORT=/tmp/realm-export.json
    configs:
      - source: realm-conf
        target: /tmp/realm-export.json
    #     Export parameters
    #    volumes:
    #      - ./keycloak-export/activage-realm.json:/tmp/realm-export.json
    #    command: -Dkeycloak.migration.realmName=activage -Dkeycloak.migration.action=export -Dkeycloak.migration.provider=singleFile -Dkeycloak.migration.file=/tmp/realm-export.json -Dkeycloak.migration.strategy=OVERWRITE_EXISTING
    networks:
      - keycloak-activage-network

configs:
  realm-conf:
    file: ./keycloak-export/activage-realm.json

networks:
  keycloak-activage-network:
    external: true
